---
devnet_day2_lab:
  connection_options:
    napalm:
      extras:
        optional_args:
          transport: 'telnet'

step_lab:
  username: cisco
  password: cisco
  connection_options:
    napalm:
      extras:
        optional_args:
          transport: 'telnet'
    netmiko:
      extras:
        device_type: 'cisco_ios_telnet'

    scrapli:
      platform: cisco_iosxe
      extras:
        transport: 'telnet'